spring:
  application:
    name: dog-service
    org: petclinic
  datasource:
    url: "jdbc:postgresql://localhost:5432/dog-db"
    username: "dog"
    password: "woof"
  jpa:
    open-in-view: false
  jmx:
    enabled: true
  mvc:
    problemdetails:
      enabled: true
  sql:
    init:
      mode: always

server:
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
    jmx:
      exposure:
        include:
        - "*"
  endpoint:
    env:
      show-values: always
  observations:
    key-values:
      org: ${spring.application.org}
  metrics:
    tags:
      application: ${spring.application.name}
      org: ${spring.application.org}

application:
  security:
    users:
    - name: "user"
      password: "password"
    - name: "admin"
      password: "secret"
      roles: ["admin"]
